### ISSUE TITLE
درخواست

### ISSUE THREAD

**Issue by shabda7** [ByteMysticRogue/Hiddify-Warp#1]
سلام. امکانش هست که کنار پروکسی‌ها یکی هم chain بذارید که ip ایران نیوفته؟ مثلا بشه از سریع‌ترین ip که اسکن شده استفاده کرد. ممنون

**Comment by ByteMysticRogue** [comment]
> سلام. امکانش هست که کنار پروکسی‌ها یکی هم chain بذارید که ip ایران نیوفته؟ مثلا بشه از سریع‌ترین ip که اسکن شده استفاده کرد. ممنون


بله اضافه میشه
