### ISSUE TITLE
روی نسخه موبایل هایدیفای کار نمیکنه

### ISSUE THREAD

**Issue by iHMahmoodi** [ByteMysticRogue/Hiddify-Warp#2]
سلام
روی نسخه موبایل هایدیفای میگه invalid هست
هم لینک و هم qr
روی کامپیوتر ولی واردش کرد

**Comment by ByteMysticRogue** [comment]
> سلام روی نسخه موبایل هایدیفای میگه invalid هست هم لینک و هم qr روی کامپیوتر ولی واردش کرد

درود، مشکلی نداره.
