### ISSUE TITLE
ارور در اضافه کردن کانفیگ (sing-box)‏‎

### ISSUE THREAD

**Issue by sepehrbrj** [ByteMysticRogue/Hiddify-Warp#4]
![Screenshot_20240626-004300](https://github.com/ByteMysticRogue/Hiddify-Warp/assets/55192376/d4051d6b-4677-41fd-9299-0a8472f8e55b)

**Comment by ByteMysticRogue** [comment]
مشکلی نداره؛ اینترنتتون رو عوض کنید درست میشه.
