### ISSUE TITLE
Api 

### ISSUE THREAD

**Issue by EEvanescence** [ByteMysticRogue/Hiddify-Warp#6]
سلام رفیق، فکر میکنم مشکل api داریم، zero team دیگه کار نمیکنه، پیشنهادی دارید برای جایگزین کردنش؟ خودتون دوباره راه میندازیدش ؟؟ خیلی عالی بود این چند وقت ، مننونم بابت تمام زحماتتون

**Comment by ByteMysticRogue** [comment]
> سلام رفیق، فکر میکنم مشکل api داریم، zero team دیگه کار نمیکنه، پیشنهادی دارید برای جایگزین کردنش؟ خودتون دوباره راه میندازیدش ؟؟ خیلی عالی بود این چند وقت ، مننونم بابت تمام زحماتتون

درود، بر حال بررسیه
تا ساعت دیگه اوکی میشه.
